name: Test develop code and create PR to staging
on:
  push:
    branches:
    - develop
    paths:
    - java-framework/**

jobs:
  build-and-test-project:
    name: Build and test phase
    strategy:
      max-parallel: 1
    uses: jpsugg/the-internet-tests/.github/workflows/java-framework-run-e2e-tests.yml@develop
    with:
      target-environment: staging
      source-branch: develop
    secrets: inherit
  
  create-pr:
    strategy:
      max-parallel: 1
    needs: build-and-test-project
    if: needs.build-and-test-project.result == 'success'
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ""
          PULL_REQUEST_BRANCH: "staging"
          PULL_REQUEST_FROM_BRANCH: "develop"
          PULL_REQUEST_TITLE: "Post-test automatic PR"
      - name: Exit Create PR process
        run: echo "Exit Create PR process"
        if: ${{ success() }}

  merge-pr:
    name: Merge develop into staging
    strategy:
      max-parallel: 1
    needs: create-pr
    if: needs.create-pr.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: jpsugg/the-internet-tests/.github/workflows/merge-develop-into-staging.yaml@develop
        with:
          environment: staging
        secrets: inherit

    dont-merge-pr:
      name: Do not merge develop into staging - something failed
      strategy:
      max-parallel: 1
      needs: create-pr
      if: needs.create-pr.result == 'failure'
      runs-on: ubuntu-latest
      steps:
        - run: echo 'Not merging. The workflow failed'
  # steps:
  # - name: Merge me!
  #   uses: ridedott/merge-me-action@v2
  #   with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
  #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  # timeout-minutes: 1
