name: Test develop code and create PR to staging

on:
  push:
    branches:
      - develop
    paths:
      - java-framework/**
      - .github/workflows/**

jobs:
  load-docker-cache:
    runs-on: ubuntu-latest
    name: Set up the docker layers cache
    steps:
      - name: Docker Layer Caching2
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
        with:
          key: services-docker-cache-{hash}
          restore-keys: |
            foo-docker-cache-

  build-and-test-project:
    name: Build and test project
    needs: load-docker-cache
    uses: jpsugg/the-internet-tests/.github/workflows/run-e2e-tests-java-framework.yml@develop
    with:
      environment: develop
      branch: develop
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      workflow-status: ${{ jobs.build-and-test.outputs.workflow-status }}
  
  create-pr:
    name: Create Pull Request
    needs: build-and-test-project
    if: ${{ needs.build-and-test-project.outputs.workflow-status == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ""
          PULL_REQUEST_BRANCH: "staging"
          PULL_REQUEST_FROM_BRANCH: "develop"
          PULL_REQUEST_TITLE: "Post-testing automated PR"
      - name: Finish PR creation
        if: ${{ steps.pr.outputs.result == 'Created PR' }}
        run: |
          echo "PR created successfully"
          echo "::set-output name=workflow-status::success"
        id: pr_status
      - if: ${{ steps.pr.outputs.result != 'Created PR' }}
        name: Failed to create PR
        run: |
          echo Failed to create the PR
          echo "::set-output name=workflow-status::failure"
        id: pr_status

    outputs:
      workflow-status: ${{ steps.pr_status.outputs.workflow-status }}

  merge-pr:
    name: Deploy to staging
    needs: create-pr
    if: needs.create-pr.outputs.workflow-status == 'success'
    uses: jpsugg/the-internet-tests/.github/workflows/merge-develop-into-staging.yaml@develop
    with:
      target-environment: staging
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  merge-pr-validation:
    name: Validate deploy success
    needs: merge-pr
    runs-on: ubuntu-latest
    steps:
      - name: Automated PR merge success
        if: ${{ needs.merge-pr.outputs.workflow-status != 'success' }}
        run: |
          echo Deployment phase failed
          exit 1

  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - name: Log error or failure
        env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
          echo Workflow failed
          exit 1
