name: Test project`s code and create PR
on:
  push:
    branches:
    - develop
    paths:
    - java-framework/**

jobs:
  build-and-test-project:
    strategy:
      max-parallel: 1
    uses: jpsugg/the-internet-tests/.github/workflows/java-framework-run-e2e-tests.yml@develop
    with:
      target-environment: ${{ inputs.target-environment }}
    secrets: inherit
    if: ${{ success() }}
    name: Finished build and test phase
  
  create-pr:
    if: ${{ success() }}
    needs: build-and-test-project
    name: Create a Pull Request to Merge develop into staging
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ""
          PULL_REQUEST_BRANCH: "staging"
          PULL_REQUEST_FROM_BRANCH: "develop"
          PULL_REQUEST_TITLE: "Post-test automatic PR"
      - name: Exit Create PR process
        run: echo "Exit Create PR process"
        if: ${{ success() }}
        
