name: Merge develop into staging

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
    outputs:
      workflow-status:
        description: "The workflow's status at the end of the execution"
        value: ${{ jobs.merge-me.outputs.job-status }}
    secrets:
      github-token:
        required: true

jobs:
  merge-me:
    name: Merge develop into staging
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    outputs:
      workflow-status: ${{ steps.set_status.outputs.workflow-status }}
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Post-testing automated PR merge
        id: merge-action
        uses: ridedott/merge-me-action@v2.10.44
        with:
          GITHUB_TOKEN: ${{ secrets.github-token }}
      - name: Set job status
        id: set_status
        run: |
          if [[ "${{ steps.merge-action.outcome }}" == "success" ]]; then
            echo "workflow-status=success" >> $GITHUB_OUTPUT
          else
            echo "workflow-status=failure" >> $GITHUB_OUTPUT
            echo "Won't merge, merge action failed"
            exit 1
          fi
    timeout-minutes: 5