name: Merge code after successful testing

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-token:
        required: true
        type: string
  # types:
  #   - completed
  # workflows:
      # List all required workflow names here.
  #   - 'Test develop code and create PR to staging'

jobs:
  merge-me:
    name: Merge develop into staging
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    uses: ridedott/merge-me-action@v2
    with:
      github-token: ${{ inputs.github-token }}
    timeout-minutes: 5