name: Merge code after successful testing

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      github-token:
        required: true
        type: string

jobs:
  merge-me:
    name: Merge develop into staging
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - if: ${{ github.event.workflow_call.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ inputs.github-token }}
    timeout-minutes: 5