name: Merge code after successful testing

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-token:
        required: true
        type: string

jobs:
  merge-me:
    name: Merge develop into staging
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    uses: ridedott/merge-me-action@v2
    with:
      github-token: ${{ inputs.github-token }}
    timeout-minutes: 5