name: Merge code after successful testing

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  merge-me:
    name: Merge develop into staging
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - if: ${{ github.event.workflow_call.conclusion == 'success' }}
        name: "Post-testing automated PR merge"
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.github-token }}
    timeout-minutes: 5