name: E2E java-framework UI tests

env:
  LOG_LEVEL: debug
  ENVIRONMENT: staging
  suiteXmlFile: regression.xml
  browser: remote-chrome
  headlessBrowser: false
  testsThreadCount: 10
  working-directory: ./java-framework
  report-directory: ./java-framework/target/surefire-reports

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: staging
        options:
          - master
          - staging
          - develop
      chromeVersion:
        description: 'Chrome Version'
        required: true
        default: '110'
        type: choice
        options:
          - "latest"
          - "110"
  workflow_call:
    inputs:
      environment:  # Target environment
        required: true
        type: string
      branch:  # Source branch
        required: true
        type: string
    secrets:
      github-token:
        required: true
  push:
    branches:
      - develop
      - staging
      - master
    paths: java-framework/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          token: ${{ secrets.github-token }}

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cached Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            cd ${{ env.working-directory }}
            mvn clean install -DsuiteXmlFile=${{ env.suiteXmlFile }} -Djava.awt.headless=${{ env.headlessBrowser }}
            env:
              BROWSER: ${{ env.browser }}
            working-directory: ${{ env.working-directory }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.report-directory }}

      - name: Set job status
        id: set_status
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "::set-output name=workflow-status::success"
          else
            echo "::set-output name=workflow-status::failure"
          fi
    outputs:
      workflow-status: ${{ steps.set_status.outputs.workflow-status }}
