# Workflow to run automated tests on java-framework code pushed to the repository
name: E2E java-framework UI tests

env:
  LOG_LEVEL: debug
  ENVIRONMENT: staging
  suiteXmlFile: regression.xml
  browser: remote-chrome
  browser-version: '110'
  headlessBrowser: false
  useSeleniumGrid: true
  testsThreadCount: 10
  working-directory: ./java-framework
  report-directory: ./java-framework/target/surefire-reports

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: true
        default: staging
        options:
          - master
          - staging
          - develop
      chromeVersion:
        description: 'Chrome Version'
        required: true
        default: '110'
        type: choice
        options:
          - "latest"
          - "110"
  workflow_call:
    inputs:
      environment:  # Target environment
        required: true
        type: string
      branch:  # Source branch
        required: true
        type: string
    secrets:
      github-token:
        required: true
  push:
    branches:
      - develop
      - staging
      - master
    paths: java-framework/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    services:
      website:
        image: gprestes/the-internet:latest
        ports:
          - 7080:5000
        options: >-
          --rm
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4442:4442
          - 4443:4443
          - 4444:4444
        options: >-
          --rm
          -v /dev/shm:/dev/shm
        env:
          SE_VNC_NO_PASSWORD: 1
          SE_SESSION_RETRY_INTERVAL: 1
          SE_START_XVFB: true
          SE_SCREEN_WIDTH: 1920
          SE_SCREEN_HEIGHT: 1080
      chrome-node-video:
        image: selenium/video:latest
        options: >-
          -v /home/runner/work/the-internet-tests/java-framework/target:/home/seluser/Downloads
          -v /home/runner/work/the-internet-tests/java-framework/target/surefire-reports:/videos
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_SESSION_RETRY_INTERVAL: 1
          SE_NODE_MAX_INSTANCES: 20
          SE_NODE_MAX_SESSIONS: 1
          SE_NODE_SESSION_TIMEOUT: 500
          SE_START_XVFB: true
          DISPLAY_CONTAINER_NAME: chrome-node
          FILE_NAME: chrome_video.mp4
      chrome-node:
        image: selenium/node-chrome:latest
        options: >-
          -v /home/runner/work/the-internet-tests/java-framework/target:/home/seluser/Downloads
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_SESSION_RETRY_INTERVAL: 1
          SE_NODE_MAX_INSTANCES: 20
          SE_NODE_MAX_SESSIONS: 4
          SE_NODE_SESSION_TIMEOUT: 500
          SE_START_XVFB: true

    steps:
      - name: Get test-runner IP
        run: echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV
      - name: Runner IP address
        run: echo "Host IP address ${{ env.ip }}"
      - name: Checkout repo code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0
      - name: Set up JDK 
    steps:
      - name: Get test-runner IP
        run: echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV
      - name: Runner IP address
        run: echo "Host IP address ${{ env.ip }}"
      - name: Checkout repo code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clean
        run: mvn clean -f pom.xml --batch-mode --update-snapshots
        working-directory: ${{env.working-directory}}
      - name: Build
        run: mvn compile -f pom.xml --batch-mode --update-snapshots
        working-directory: ${{env.working-directory}}
      - name: Run the test suite
        run: >-
          mvn test -f pom.xml
          --batch-mode --update-snapshots -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ env.LOG_LEVEL }}
        working-directory: ${{ env.working-directory }}
        env:
          browserVersion: ${{ env.browser-version }}
          headlessBrowser: false
          testRunnerAppAddress: "http://172.17.0.1:7080"
          webAppAddress: "http://172.17.0.1:7080"
          seleniumGridAddress: "http://172.17.0.1:4444/wd/hub"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test run report
          path: ${{ env.report-directory }}
      - name: Display structure of uploaded files
        run: ls -R
        working-directory: ${{env.report-directory}}
